### ISSUE TITLE
issues with "famous develop"

### ISSUE THREAD

**Issue by bgamut** [Famous/famous-cli#72]
bash-3.2# famous develop

> engine-seed@1.0.0 dev /Users/ahnbernard/famous
> node ./bin/dev.js

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Object.<anonymous> (/Users/ahnbernard/famous/bin/dev.js:58:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! engine-seed@1.0.0 dev: `node ./bin/dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the engine-seed@1.0.0 dev script 'node ./bin/dev.js'.
npm ERR! This is most likely a problem with the engine-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/dev.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls engine-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ahnbernard/famous/npm-debug.log
child process exited with code 1
bash-3.2# 

////////////  npm-debug.log/////////

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev engine-seed@1.0.0
6 info dev engine-seed@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info engine-seed@1.0.0 Failed to exec dev script
9 verbose stack Error: engine-seed@1.0.0 dev: `node ./bin/dev.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid engine-seed@1.0.0
11 verbose cwd /Users/ahnbernard/famous
12 error Darwin 13.4.0
13 error argv "node" "/usr/local/bin/npm" "run" "dev"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error engine-seed@1.0.0 dev: `node ./bin/dev.js`
17 error Exit status 1
18 error Failed at the engine-seed@1.0.0 dev script 'node ./bin/dev.js'.
18 error This is most likely a problem with the engine-seed package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/dev.js
18 error You can get their info via:
18 error     npm owner ls engine-seed
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by TheAlphaNerd** [comment]
looks like you have a node instance running

try �killall node"

**Comment by bgamut** [comment]
Thanks! I don't know what I just typed in. but after your advice the error message shortened to

AhnBernards-MacBook-Pro:famous ahnbernard$ famous develop
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy

TypeError: Bad argument
    at TypeError (native)
    at Object.fs.closeSync (fs.js:469:18)
    at /usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:5:8090
    at /usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:1:6062
    at /usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:5:7956
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by TheAlphaNerd** [comment]
Just do 

```npm run dev```

don�t bother using the cli
